### ISSUE TITLE
Transformation deserialization from a config file

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#428]
I would like to know your opinion about the following code to add to torchvision. 
Suppose I have a configuration yaml file:
```yaml
"Compose":
    "transforms":
      - "ToThreeBands":
      - "ToPILImage":
      - "RandomApply":
          "p": 0.85
          "transforms":
            - "RandomAffine":
                "degrees": [-45, 45]
                "translate": [0.15, 0.15]
                "scale": [1.0, 1.2]
            - "RandomHorizontalFlip":
            - "RandomVerticalFlip":
      - "ToTensor":
      - "_Normalize":
```
that I would like to deserialize into `torchvision.transforms.transforms.Compose`.

The following can be done like this:
```python
from torchvision import transforms

_GLOBAL_PYTORCH_OBJECTS = dict([(name, cls) for name, cls in transforms.__dict__.items() if isinstance(cls, type)])

def deserialize(data, custom_objects=None):
    if isinstance(data, dict):        
        # Deserialize dictionary
        obj_dict = dict(data)
        for key in obj_dict:
            value = obj_dict[key]
            value = deserialize(value, custom_objects=custom_objects)
            if key in custom_objects:                    
                cls = custom_objects[key]
                return cls(**value) if value is not None else cls()
            obj_dict[key] = value
        return obj_dict            
    elif isinstance(data, (tuple, list)):
        # iterate over 
        return [deserialize(d, custom_objects=custom_objects) for d in data]
    else:
        return data

transforms_config = {....}  # Deserialized YAML

class ToThreeBands(object): pass
     #  My custom class to transform input images
     # ....

class _Normalize(object): pass
     #  My custom class to normalize tensors
     # ....

custom_objects = dict(_GLOBAL_PYTORCH_OBJECTS)
custom_objects.update({
    "ToThreeBands": ToThreeBands,
    "_Normalize": _Normalize
})

res = deserialize(transforms_config, custom_objects=custom_objects)
for t in res.transforms:
    print(type(t), t)
    if hasattr(t, "transforms"):
        for tt in t.transforms:
            print(type(tt), tt)
```
with the output:
```
<class '__main__.ToThreeBands'> <__main__.ToThreeBands object at 0x7f43e30cacc0>
<class 'torchvision.transforms.transforms.ToPILImage'> ToPILImage()
<class 'torchvision.transforms.transforms.RandomApply'> RandomApply(
    p=0.85
    RandomAffine(degrees=[-45, 45], translate=[0.15, 0.15], scale=[1.0, 1.2])
    RandomHorizontalFlip(p=0.5)
    RandomVerticalFlip(p=0.5)
)
<class 'torchvision.transforms.transforms.RandomAffine'> RandomAffine(degrees=[-45, 45], translate=[0.15, 0.15], scale=[1.0, 1.2])
<class 'torchvision.transforms.transforms.RandomHorizontalFlip'> RandomHorizontalFlip(p=0.5)
<class 'torchvision.transforms.transforms.RandomVerticalFlip'> RandomVerticalFlip(p=0.5)
<class 'torchvision.transforms.transforms.ToTensor'> ToTensor()
<class '__main__._Normalize'> <__main__._Normalize object at 0x7f43e3022d30>
```
Any feedback is highly apreciated :)
Thanks

**Comment by fmassa** [comment]
Hi,

While this is an interesting idea, I wonder if it wouldn't be in some sense easier to have your configuration file be a python file, where you directly define the transform that you want? This reminds me of Lua, which was originally developed for that :)

This has the benefit of having better error reporting if you have a typo in one of your functions/names for example

What do you think?

**Comment by vfdev-5** [comment]
Yes, maybe a python file will be easier to code and less error prone, but probably less obvious what is configuration and what is working script.
An example use-case I see behind such deserialization:  let's say there is a script `train.py` that takes a `train_config.yaml` as a single argument:
```bash
python train.py train_config.yaml
```
Such `train_config.yaml`  can be something like:
```
n_epochs: 100
batch_size: 32
...
model: 
   MySuperModel:
      n_classes: 12
      n_channels: 3      
....
train_transforms:
  Compose:
    transforms:
      - ToThreeBands:
      - ToPILImage:
      - RandomApply:
          p: 0.85
          transforms:
            - RandomAffine:
                degrees: [-45, 45]
                translate: [0.15, 0.15]
                scale: [1.0, 1.2]
            - RandomHorizontalFlip:
            - RandomVerticalFlip:
      - ToTensor:
      - _Normalize:
```
and the script `train.py` deserializes  all parameters, objects and assembles all together to run a training.

The same can be done with a python config file, where we can code directly a transformation as `torchvision` objects (but I'm less fan)
